---
repo-name: peripherals-aveksa
categories:
- Identity Management
display-name: Aveksa
manufacture: Aveksa
product: Aveksa
description: Aveksa 3 is the industry’s only comprehensive Enterprise Access Governance solution. It enables automated, auditable business processes for the management, monitoring, reporting and remediation of access rights to enterprise information assets, while enforcing accountability and enabling key stakeholders to collaborate to achieve good governance. 

